### ISSUE TITLE
`skeleton_mesh.png` copyright issue

### ISSUE THREAD

**Issue by MoNTE48** [AntumMT/mod-cmer_skeleton#1]
Hello.
I am the author and owner of `skeleton_mesh.png` texture and this texture has never been licensed under **CC BY-SA 3.0**.
But I authorize you to use it without restriction under **CC BY-SA 4.0** license, attributed as **(C) 2016 MultiCraft Development Team**.

https://github.com/MultiCraft/MultiCraft_game/commits/bd46d528d7140cf6e7173e883323ec75506708d6/files/mobs/textures/mobs_skeleton.png

Have a nice day 🤓

**Comment by AntumDeluge** [comment]
Thank you so much for contacting me. I got the skeleton_mesh image from [Addis Open MT-Skin Database](http://minetest.fensta.bplaced.net/#id=1141). If you have not contacted them, you should do so as well.

I will update the license & attribution. Thank you again.

**Comment by AntumDeluge** [comment]
I attributed you as "MoNTE48". Is that sufficient?
3cd6277

**Edit:** Sorry, I just realized you posted how it should be attributed. I will fix that.
